# Values Schema

architecture: replication # standalone

# auth:
  # rootPassword: # ""
  # createDatabase: # true
  # database: # my_database
  # username: # ""
  # password: # ""
  # replicationUser: # replicator
  # replicationPassword: # ""

metrics:
  enabled: true # false

# Primary database configuration
primary: 
  # Enable persistence using Persistent Volume Claims
  persistence: 
    # If true, use a Persistent Volume Claim, If false, use emptyDir
    enabled: true
  # MySQL primary Pod security context
  podSecurityContext: 
    enabled: false
    fsGroup: 1001
  # MySQL primary container security context
  containerSecurityContext: 
    enabled: false
    runAsUser: 1001

# Secondary database configuration
secondary: 
  # Enable persistence using Persistent Volume Claims
  persistence: 
    # If true, use a Persistent Volume Claim, If false, use emptyDir
    enabled: true
  # MySQL secondary Pod security context
  podSecurityContext: 
    enabled: false
    fsGroup: 1001
  # MySQL secondary container security context
  containerSecurityContext: 
    enabled: false
    runAsUser: 1001
