# https://github.com/prometheus/node_exporter
# 
# docker compose -f exporter-linux.yaml up
# - http://localhost:9100
# - http://localhost:9100/metrics

services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - --path.rootfs=/host
      # - --web.listen-address=:9100
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave
